##To those new to active directory: Changing a dc's hostname after first boot (pdc role promotion) will ruin the AD.
#
##In this example:
##Start a new domain, and forward non-resolvable queries to Cloudflare's DNS server.
##Use the .env file to configure subnet and other environment variables.
#
##Keep in mind for all examples DOMAINPASS can be removed after the first run.
version: '2'

networks:
  extnet:
    external: true

services:

# ----------- samba begin ----------- #

  samba:
    image: nowsci/samba-domain
    container_name: samba
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/:/var/lib/samba
      - ./config/samba:/etc/samba/external
    environment:
      - DOMAIN=DOMAIN.LOCAL
      - DOMAINPASS=7r713p0w3r
      - DNSFORWARDER=$DNS_FORWARDER
    networks:
      - extnet
    ports:
      - $DC_IP:53:53
      - $DC_IP:53:53/udp
      - $DC_IP:88:88
      - $DC_IP:88:88/udp
      - $DC_IP:135:135
      - $DC_IP:137-138:137-138/udp
      - $DC_IP:139:139
      - $DC_IP:389:389
      - $DC_IP:389:389/udp
      - $DC_IP:445:445
      - $DC_IP:464:464
      - $DC_IP:464:464/udp
      - $DC_IP:636:636
      - $DC_IP:1024-1044:1024-1044
      - $DC_IP:3268-3269:3268-3269
    dns_search:
      - domain.local
    dns:
      - $DC_IP
      - $DNS_FORWARDER
    extra_hosts:
      - dc0.domain.local:$DC_IP
    hostname: dc0
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    privileged: true
    restart: always

# ----------- samba end ----------- #
